spring:
  application:
    name: bonus-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bonus_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: bonus-service


server:
  port: 8080
