spring:
  application:
    name: bonus-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bonus_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  logging:
    level:
      liquibase: DEBUG

server:
  port: 8080
